### PR TITLE
Fix issue ORDER BY column# Does Not Work #890

### LINKED ISSUE #890: ORDER BY column# Does Not Work
If the sort expression in an `ORDER BY` clause is a single number, then it is supposed to represent an output column from the `SELECT`.

```
terrier=# CREATE TABLE xxx (id INT PRIMARY KEY, val VARCHAR);
terrier=# INSERT INTO xxx VALUES (1,'c'),(2,'b'),(3,'a');
terrier=# SELECT id, val FROM xxx ORDER BY 2;
 id | val 
----+-----
  1 | c
  2 | b
  3 | a
(3 rows)
```

The correct output (as observed in Postgres) should be:
```
pavlo=# SELECT id, val FROM xxx ORDER BY 2;             
 id | val 
----+-----
  3 | a
  2 | b
  1 | c
(3 rows)
```

### PR DESCRIPTION
**Pull request by wgy8283335**
Fix #890

---

Fix issue ORDER BY column# Does Not Work #890

### CODE REVIEW

**Comment by apavlo** [comment]
@wgy8283335 Nice work! See our PR instructions: https://github.com/cmu-db/terrier/wiki/Pull-Request-Process

**Comment by mbutrovich** [comment]
Can you add a test case that fails on current master and is fixed by this PR?

**Comment by wgy8283335** [comment]
> Can you add a test case that fails on current master and is fixed by this PR?

OK

**Comment by wgy8283335** [comment]
@mbutrovich Hello, it seems that the checks have passed. But, I'd like to discuss the unit test that is added in. 
I change the code line `pqxx::result r = txn1.exec("SELECT id,data,num FROM TableB ORDER BY 3");` to `pqxx::result r = txn1.exec("SELECT id,data,num FROM TableB ORDER BY num");`. 
Because, with  `pqxx::result r = txn1.exec("SELECT id,data,num FROM TableB ORDER BY 3");`, the test case could succeed when executing independently, but fail when executing in 'unittest' target.

**Comment by wgy8283335** [comment]
@apavlo Dear Professor Pavlo, I've followed the instruction of the pull request process. Now, I'm blocked in ci. And I have no idea of dealing this problem. Could you help me? The description of the problem is below:
```
+ cd build

+ timeout 10m python3 ../script/testing/oltpbench/run_oltpbench.py tatp 2,35,10,35,2,14,2 --build-type=debug --scale-factor=0.01 --loader-threads=4

Failed to connect to DB server [Attempt #20/50]

Traceback (most recent call last):

  File "/jenkins/workspace/terrier_PR-964/script/testing/util/test_server.py", line 132, in wait_for_db

    s.connect((self.db_host, int(self.db_port)))

ConnectionRefusedError: [Errno 111] Connection refused

Failed to connect to DB server [Attempt #40/50]

Traceback (most recent call last):

  File "/jenkins/workspace/terrier_PR-964/script/testing/util/test_server.py", line 132, in wait_for_db

    s.connect((self.db_host, int(self.db_port)))

ConnectionRefusedError: [Errno 111] Connection refused

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

DATABASE OUTPUT

Traceback (most recent call last):

  File "/jenkins/workspace/terrier_PR-964/script/testing/util/test_server.py", line 100, in run_db

    self.wait_for_db()

  File "/jenkins/workspace/terrier_PR-964/script/testing/util/test_server.py", line 154, in wait_for_db

    raise RuntimeError(msg)

RuntimeError: Unable to connect to DBMS [PID=8123 / RUNNING]

Failed to connect to DB server [Attempt #20/50]

Traceback (most recent call last):

  File "/jenkins/workspace/terrier_PR-964/script/testing/util/test_server.py", line 132, in wait_for_db

    s.connect((self.db_host, int(self.db_port)))

ConnectionRefusedError: [Errno 111] Connection refused

Connected to server in 7.6000000000000005 seconds [PID=8139]

Buildfile: /tmp/oltpbench/build.xml
```

**Comment by apavlo** [comment]
@wgy8283335 There is a random bug in our test script where it sometimes cannot connect to the right DBMS instance. We haven't been able to track it down. I will monitor your builds and restart it until it passes. Thanks for checking on it.

File: test/traffic_cop/traffic_cop_test.cpp [hunk 1]
```diff
@@ -144,6 +145,28 @@ TEST_F(TrafficCopTests, BasicTest) {
...
+    pqxx::connection connection(fmt::format("host=127.0.0.1 port={0} user={1} sslmode=disable application_name=psql",
+                                            port_, catalog::DEFAULT_DATABASE));
+
+    pqxx::work txn1(connection);
+    txn1.exec("DROP TABLE IF EXISTS TableB");
+    txn1.exec("CREATE TABLE TableB (id INT PRIMARY KEY, data TEXT, num INT);");
+    txn1.exec("INSERT INTO TableB VALUES (1, 'abc', 3);");
+    txn1.exec("INSERT INTO TableB VALUES (2, 'abc', 2);");
+    txn1.exec("INSERT INTO TableB VALUES (3, 'abc', 1);");
+    pqxx::result r = txn1.exec("SELECT id,data,num FROM TableB ORDER BY num");
```
Comment (apavlo) [inline test/traffic_cop/traffic_cop_test.cpp:160]: How does this actually test ORDER BY column#? It is ordering by the column name.

You should execute two queries and check that output is the same:

1. `SELECT id,data,num FROM TableB ORDER BY num`
2. `SELECT id,data,num FROM TableB ORDER BY 3`

Comment (wgy8283335) [reply test/traffic_cop/traffic_cop_test.cpp:160]: @apavlo , Dear Professor Apavlo. I've modified the test case. And when I execute the test separately, it could succeed. But when I build the "unittest" target, the test case fails.
gtest1
gtest2

Comment (wgy8283335) [reply test/traffic_cop/traffic_cop_test.cpp:160]: Below is the unit test case.
```
TEST_F(TrafficCopTests, OrderTest) {
  try {
    pqxx::connection connection(fmt::format("host=127.0.0.1 port={0} user={1} sslmode=disable application_name=psql",
                                            port_, catalog::DEFAULT_DATABASE));

    pqxx::work txn1(connection);
    txn1.exec("DROP TABLE IF EXISTS TableA");
    txn1.exec("CREATE TABLE TableA (id INT PRIMARY KEY, data TEXT, num INT);");
    txn1.exec("INSERT INTO TableA VALUES (1, 'abc', 3);");
    txn1.exec("INSERT INTO TableA VALUES (2, 'abc', 2);");
    txn1.exec("INSERT INTO TableA VALUES (3, 'abc', 1);");
    pqxx::result r1 = txn1.exec("SELECT id,data,num FROM TableA ORDER BY num");
    pqxx::result r2 = txn1.exec("SELECT id,data,num FROM TableA ORDER BY 3");
    int value1 = 0;
    r1.begin().at(0).to(value1);
    int value2 = -1;
    r2.begin().at(0).to(value2);
    EXPECT_EQ(value1, value2);
    txn1.commit();
  } catch (const std::exception &e) {
    EXPECT_TRUE(false);
  }
}
```

**Comment by apavlo** [comment]
Move your test case to `SelectTest.java`. It doesn't belong in `traffic_cop_tests`. 

@dniu16 will then convert it to the new sqlite trace format file once this is merged.

File: src/traffic_cop/traffic_cop_util.cpp [hunk 2]
```diff
@@ -51,11 +53,27 @@ std::unique_ptr<planner::AbstractPlanNode> TrafficCopUtil::Optimize(
       auto types = order_by->GetOrderByTypes();
       auto exprs = order_by->GetOrderByExpressions();
       for (size_t idx = 0; idx < order_by->GetOrderByExpressionsSize(); idx++) {
+        if (exprs[idx].Get()->GetExpressionType() == terrier::parser::ExpressionType::VALUE_CONSTANT) {
```
Comment (apavlo) [inline src/traffic_cop/traffic_cop_util.cpp:56]: 1. This logic is somewhat complex and difficult to read. Please add documentation that explains what it does.
2. Add a comment that this should be moved into the binder or optimizer. TrafficCopUtil isn't the right place for this.

File: src/traffic_cop/traffic_cop_util.cpp [hunk 3]
```diff
@@ -51,11 +53,27 @@ std::unique_ptr<planner::AbstractPlanNode> TrafficCopUtil::Optimize(
...
+          common::ManagedPointer<parser::ConstantValueExpression> constant_value_expression =
+              exprs[idx].CastManagedPointerTo<parser::ConstantValueExpression>();
+          int64_t column_id = constant_value_expression->GetInteger().val_;
```
Comment (apavlo) [inline src/traffic_cop/traffic_cop_util.cpp:59]: What happens if the `ConstantValueExpression` is not an integer?

File: test/traffic_cop/traffic_cop_test.cpp [hunk 4]
```diff
@@ -133,6 +133,7 @@ TEST_F(TrafficCopTests, BasicTest) {
                                             port_, catalog::DEFAULT_DATABASE));
 
     pqxx::work txn1(connection);
+    txn1.exec("DROP TABLE IF EXISTS TableA");
```
Comment (apavlo) [inline test/traffic_cop/traffic_cop_test.cpp:136]: Is this still needed?

File: src/traffic_cop/traffic_cop_util.cpp (hunk 2 above)
Comment (lmwnshn) [inline src/traffic_cop/traffic_cop_util.cpp:56]: Hi! Thanks for the PR.

You might want to consider moving the logic into the Binder instead, see [0]. I think you might be able to do this as part of the Binder's visitor pattern, see [1] for an example (essentially, you are given that [2] will be called, which will call [3], and your code can piggyback on that).

Also, please note that whenever you create a new expression (the parser::ColumnValueExpression below) that you should figure out who's going to own it. If you're in the Binder, you could push it into the sherpa's ParseResult, e.g. [4].

1. This would let you support both ORDER BY (number) and ORDER BY (column name) with pretty much the same code, e.g., you could turn the column name into the index and use your existing code.
2. This lets you throw errors for "invalid column index" and "invalid table name" -- these aren't parsing errors, so the earliest place you can throw it is in the binder.


(all psql snippets from postgres)

```
psql=> select * from foo order by bar;
ERROR:  column "bar" does not exist
LINE 1: select * from foo order by bar;
```

```
psql=> select * from foo order by 2;
ERROR:  ORDER BY position 2 is not in select list
LINE 1: select * from foo order by 2;
```

[0] https://github.com/cmu-db/terrier/blob/master/src/binder/bind_node_visitor.cpp#L728
[1] https://github.com/cmu-db/terrier/pull/831/files#diff-30e70da0e63e3710075e791cb17a2caaR56
[2] https://github.com/cmu-db/terrier/blob/master/src/binder/bind_node_visitor.cpp#L466
[3] https://github.com/cmu-db/terrier/blob/master/src/binder/bind_node_visitor.cpp#L728
[4] https://github.com/cmu-db/terrier/blob/master/src/binder/bind_node_visitor.cpp#L384

Comment (wgy8283335) [reply src/traffic_cop/traffic_cop_util.cpp:56]: Thank you, Professor Pavlo. I'd like to move this logic to the binder.

File: src/traffic_cop/traffic_cop_util.cpp (hunk 3 above)
Comment (wgy8283335) [reply src/traffic_cop/traffic_cop_util.cpp:59]: This is a bug, I will fix it.

File: test/traffic_cop/traffic_cop_test.cpp (hunk 4 above)
Comment (wgy8283335) [reply test/traffic_cop/traffic_cop_test.cpp:136]: No, this is not needed. I'd like to remove this.

File: src/traffic_cop/traffic_cop_util.cpp (hunk 2 above)
Comment (wgy8283335) [reply src/traffic_cop/traffic_cop_util.cpp:56]: Thank you very much for your suggestion.

File: src/binder/bind_node_visitor.cpp [hunk 5]
```diff
@@ -569,14 +573,18 @@ void BindNodeVisitor::Visit(common::ManagedPointer<parser::ColumnValueExpression
...
   // TODO(Ling): consider remove precondition check if the *_oid_ will never be initialized till binder
   //  That is, the object would not be initialized using ColumnValueExpression(database_oid, table_oid, column_oid)
   //  at this point
   if (expr->GetTableOid() == catalog::INVALID_TABLE_OID) {
     std::tuple<catalog::db_oid_t, catalog::table_oid_t, catalog::Schema> tuple;
     std::string table_name = expr->GetTableName();
     std::string col_name = expr->GetColumnName();
-
+    if (table_name.empty() && col_name.empty() && expr->GetColumnOid() != catalog::INVALID_COLUMN_OID) {
+      throw BINDER_EXCEPTION(fmt::format("ORDER BY position \"{}\" is not in select list", expr->GetColumnOid()),
```
Comment (apavlo) [inline src/binder/bind_node_visitor.cpp:585]: You have to cast `col_oid_t` correctly. This does not compile.

Comment (wgy8283335) [reply src/binder/bind_node_visitor.cpp]: @apavlo Dear Professor Pavlo. The unit test always fail during ci. I've tried about 10 times, it still could not succeed. And I promise that the unit test could succeed in my local pc with ubuntu system.

**Comment by apavlo** [comment]
@wgy8283335 We are ready to merge this now! But first we need you to move your SQL queries into our new test trace files.

Can you remove your code in `SelectTest.java`? Then @dniu16 will add your code from `testSelectWithOrderBy()` into our new files: https://github.com/cmu-db/noisepage-testfiles/tree/master/sql_trace/select

**Comment by wgy8283335** [comment]
> @wgy8283335 We are ready to merge this now! But first we need you to move your SQL queries into our new test trace files.
> 
> Can you remove your code in `SelectTest.java`? Then @dniu16 will add your code from `testSelectWithOrderBy()` into our new files: https://github.com/cmu-db/noisepage-testfiles/tree/master/sql_trace/select

**Comment by wgy8283335** [comment]
@apavlo, I've modified the file and commit again.

**Comment by apavlo** [comment]
@wgy8283335 Your code fails on the following query:

```
terrier=# CREATE TABLE xxx (col1 INT, col2 INT, col3 INT);
CREATE TABLE
terrier=# INSERT INTO xxx VALUES (1,2,3),(2,1,3),(3,0,1),(4,-1,3);
INSERT 0 4
terrier=# SELECT * FROM xxx;
 col1 | col2 | col3 
------+------+------
    1 |    2 |    3
    2 |    1 |    3
    3 |    0 |    1
    4 |   -1 |    3
(4 rows)
terrier=# SELECT * FROM xxx ORDER BY 1.0 DESC;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

**Server**
```
terrier: /tmp/terrier/src/include/parser/expression/constant_value_expression.h:121: terrier::execution::sql::Integer terrier::parser::ConstantValueExpression::GetInteger() const: Assertion `(std::holds_alternative<execution::sql::Integer>(value_)) && ("Invalid variant type for Get.")' failed.
Aborted (core dumped)

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff52308b1 in __GI_abort () at abort.c:79
#2  0x00007ffff522042a in __assert_fail_base (fmt=0x7ffff53a7a38 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x555557c35460 "(std::holds_alternative<execution::sql::Integer>(value_)) && (\"Invalid variant type for Get.\")", 
    file=file@entry=0x555557c352c0 "/tmp/terrier/src/include/parser/expression/constant_value_expression.h", line=line@entry=121, 
    function=function@entry=0x555557c378e0 <terrier::parser::ConstantValueExpression::GetInteger() const::__PRETTY_FUNCTION__> "terrier::execution::sql::Integer terrier::parser::ConstantValueExpression::GetInteger() const") at assert.c:92
#3  0x00007ffff52204a2 in __GI___assert_fail (assertion=0x555557c35460 "(std::holds_alternative<execution::sql::Integer>(value_)) && (\"Invalid variant type for Get.\")", 
    file=0x555557c352c0 "/tmp/terrier/src/include/parser/expression/constant_value_expression.h", line=121, 
    function=0x555557c378e0 <terrier::parser::ConstantValueExpression::GetInteger() const::__PRETTY_FUNCTION__> "terrier::execution::sql::Integer terrier::parser::ConstantValueExpression::GetInteger() const")
    at assert.c:101
#4  0x0000555556086263 in terrier::parser::ConstantValueExpression::GetInteger (this=0x60e000066020) at /tmp/terrier/src/include/parser/expression/constant_value_expression.h:121
#5  0x00005555561cf999 in terrier::binder::BindNodeVisitor::UnifyOrderByExpression (this=0x7fff6dea7a60, order_by_description=..., select_items=std::vector of length 3, capacity 3 = {...})
    at /tmp/terrier/src/include/binder/bind_node_visitor.h:128
#6  0x00005555561c63a7 in terrier::binder::BindNodeVisitor::Visit (this=0x7fff6dea7a60, node=...) at /tmp/terrier/src/binder/bind_node_visitor.cpp:497
#7  0x00005555560b98e8 in terrier::parser::SelectStatement::Accept (this=0x60b000020b70, v=...) at /tmp/terrier/src/include/parser/select_statement.h:349
#8  0x00005555561bba7c in terrier::binder::BindNodeVisitor::BindNameToNode (this=0x7fff6dea7a60, parse_result=..., parameters=..., desired_parameter_types=...) at /tmp/terrier/src/binder/bind_node_visitor.cpp:58
#9  0x000055555618d7b0 in terrier::trafficcop::TrafficCop::BindQuery (this=0x606000011480, connection_ctx=..., statement=..., parameters=...) at /tmp/terrier/src/traffic_cop/traffic_cop.cpp:284
#10 0x0000555555fe2d2b in terrier::network::SimpleQueryCommand::Exec (this=0x60400002a090, interpreter=..., out=..., t_cop=..., connection=...) at /tmp/terrier/src/network/postgres/postgres_network_commands.cpp:144
#11 0x0000555556031073 in terrier::network::PostgresProtocolInterpreter::Process (this=0x611000039fc0, in=..., out=..., t_cop=..., context=...) at /tmp/terrier/src/network/postgres/postgres_protocol_interpreter.cpp:45
#12 0x0000555556a25586 in terrier::network::ConnectionHandle::Process (this=0x61300001ff50) at /tmp/terrier/src/include/network/connection_handle.h:121
#13 0x0000555556a21498 in terrier::network::ConnectionHandle::StateMachine::<lambda(terrier::common::ManagedPointer<terrier::network::ConnectionHandle>)>::operator()(terrier::common::ManagedPointer<terrier::network::ConnectionHandle>) const (__closure=0x0, w=...) at /tmp/terrier/src/network/connection_handle.cpp:105
#14 0x0000555556a214b7 in terrier::network::ConnectionHandle::StateMachine::<lambda(terrier::common::ManagedPointer<terrier::network::ConnectionHandle>)>::_FUN(terrier::common::ManagedPointer<terrier::network::ConnectionHandle>) () at /tmp/terrier/src/network/connection_handle.cpp:105
#15 0x0000555556a232ee in terrier::network::ConnectionHandle::StateMachine::Accept (this=0x61300001ff70, action=terrier::network::Transition::WAKEUP, connection=...) at /tmp/terrier/src/network/connection_handle.cpp:155
#16 0x0000555556414f29 in terrier::network::ConnectionHandle::HandleEvent (this=0x61300001ff50, fd=124, flags=2) at /tmp/terrier/src/include/network/connection_handle.h:96
#17 0x0000555556a25616 in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::operator()(int, short, void*) const (__closure=0x0, fd=124, flags=2, arg=0x61300001ff50)
    at /tmp/terrier/src/include/network/connection_handle.h:152
#18 0x0000555556a25645 in terrier::network::ConnectionHandle::UpdateEventFlags(short, int)::{lambda(int, short, void*)#1}::_FUN(int, short, void*) () at /tmp/terrier/src/include/network/connection_handle.h:152
#19 0x00007ffff69c88f8 in ?? () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#20 0x00007ffff69c933f in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.1.so.6
#21 0x000055555640fd74 in terrier::EventUtil::EventBaseDispatch (base=0x617000010000) at /tmp/terrier/src/include/common/event_util.h:92
#22 0x000055555640fe0f in terrier::common::NotifiableTask::EventLoop (this=0x610000008040) at /tmp/terrier/src/include/common/notifiable_task.h:159
#23 0x0000555556414a42 in terrier::common::NotifiableTask::RunTask (this=0x610000008040) at /tmp/terrier/src/include/common/notifiable_task.h:166
#24 0x0000555556410264 in terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}::operator()() const (
    __closure=0x6030000449e8) at /tmp/terrier/src/include/common/dedicated_thread_registry.h:83
#25 0x0000555556411a51 in std::__invoke_impl<void, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(std::__invoke_other, terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) (__f=...)
    at /usr/include/c++/7/bits/invoke.h:60
#26 0x0000555556410f02 in std::__invoke<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}>(terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}&&) (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#27 0x0000555556412ebc in std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x6030000449e8) at /usr/include/c++/7/thread:234
#28 0x0000555556412e8d in std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> >::operator()() (this=0x6030000449e8) at /usr/include/c++/7/thread:243
#29 0x0000555556412e6c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<terrier::common::ManagedPointer<terrier::network::ConnectionHandlerTask> terrier::common::DedicatedThreadRegistry::RegisterDedicatedThread<terrier::network::ConnectionHandlerTask, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory> >(terrier::common::DedicatedThreadOwner*, int, terrier::common::ManagedPointer<terrier::network::ConnectionHandleFactory>)::{lambda()#1}> > >::_M_run() (this=0x6030000449e0) at /usr/include/c++/7/thread:186
#30 0x00007ffff5c546df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#31 0x00007ffff6c026db in start_thread (arg=0x7fff6dea9700) at pthread_create.c:463
#32 0x00007ffff5311a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by wgy8283335** [comment]
@apavlo I've fixed the bug when order by decimal.

**Comment by apavlo** [comment]
Another problem. You are assuming that the constant is always a numeric:
```
terrier=# SELECT * FROM xxx ORDER BY 'a' DESC;
ERROR:  42703: ORDER BY position "4294967295" is not in select list
LOCATION:  /tmp/terrier/src/binder/bind_node_visitor.cpp:587
```

Postgres gives you this error:
```
pavlo=# SELECT * FROM xxx ORDER BY 'a' DESC;
ERROR:  42601: non-integer constant in ORDER BY
LINE 1: SELECT * FROM xxx ORDER BY 'a' DESC;
```

**Comment by wgy8283335** [comment]
I thought order by only support column name or numeric. When order by char or non numeric, what kind of reply should be expected?

**Comment by wgy8283335** [comment]
@apavlo  I've committed the modification.

File: src/traffic_cop/traffic_cop_util.cpp [hunk 6]
```diff
@@ -10,6 +10,8 @@
 #include "optimizer/query_to_operator_transformer.h"
 #include "optimizer/statistics/stats_storage.h"
 #include "parser/drop_statement.h"
+#include "parser/expression/column_value_expression.h"
+#include "parser/expression/constant_value_expression.h"
```
Comment (apavlo) [inline src/traffic_cop/traffic_cop_util.cpp:14]: Why do you need to include these files here?

File: src/include/binder/bind_node_visitor.h [hunk 7]
```diff
@@ -114,6 +117,32 @@ class BindNodeVisitor : public SqlNodeVisitor {
                                common::ErrorCode::ERRCODE_FEATURE_NOT_SUPPORTED);
     }
   }
+
+  std::vector<common::ManagedPointer<parser::AbstractExpression>> UnifyOrderByExpression(
```
Comment (apavlo) [inline src/include/binder/bind_node_visitor.h:121]: We are trying to improve our compilation times. Please move this function into `bind_node_visitor.cpp`

Comment (apavlo) [inline src/include/binder/bind_node_visitor.h:121]: Missing function documentation. What does this function do? What are the parameters?

File: src/include/binder/bind_node_visitor.h [hunk 8]
```diff
@@ -114,6 +117,32 @@ class BindNodeVisitor : public SqlNodeVisitor {
...
+    for (size_t idx = 0; idx < size; idx++) {
+      if (exprs[idx].Get()->GetExpressionType() == terrier::parser::ExpressionType::VALUE_CONSTANT) {
+        auto constant_value_expression = exprs[idx].CastManagedPointerTo<parser::ConstantValueExpression>();
+        type::TypeId type = constant_value_expression->GetReturnValueType();
+        int64_t column_id = 0;
+        if (type == type::TypeId::INTEGER) {
+          column_id = constant_value_expression->GetInteger().val_;
+        } else if (type == type::TypeId::DECIMAL) {
+          column_id = constant_value_expression->GetReal().val_;
+        }
```
Comment (apavlo) [inline src/include/binder/bind_node_visitor.h:135]: What about other data types? You may want to make this a `switch` and then have a default option.

File: src/include/binder/bind_node_visitor.h [hunk 9]
```diff
@@ -114,6 +117,32 @@ class BindNodeVisitor : public SqlNodeVisitor {
...
+        if (column_id > 0 && static_cast<size_t>(column_id) <= select_items.size()) {
+          exprs[idx] = select_items[column_id - 1];
+        } else {
+          exprs[idx] = common::ManagedPointer<parser::AbstractExpression>(new parser::ColumnValueExpression(
+              catalog::INVALID_TABLE_OID, catalog::INVALID_COLUMN_OID, type::TypeId::INVALID));
```
Comment (apavlo) [inline src/include/binder/bind_node_visitor.h:140]: Is this how you are specifying that there was an error in the binding? This seems hacky.

@mbutrovich What would be a better approach? Should it throw an exception?

Comment (mbutrovich) [reply src/include/binder/bind_node_visitor.h:140]: Yeah, I'd do a bounds check first rather than an if-else structure.
```
if (column_id < 1 || column_id >select_items.size()) THROW
exprs[idx] = select_items[column_id - 1];
```

File: src/traffic_cop/traffic_cop_util.cpp (hunk 6 above)
Comment (wgy8283335) [reply src/traffic_cop/traffic_cop_util.cpp]: I've deleted these lines.

File: src/include/binder/bind_node_visitor.h (hunk 7 above)
Comment (wgy8283335) [reply src/include/binder/bind_node_visitor.h]: I've modified this.

Comment (wgy8283335) [reply src/include/binder/bind_node_visitor.h]: I've added documentation comment upon the UnifyOrderByExpression function.

File: src/include/binder/bind_node_visitor.h (hunk 8 above)
Comment (wgy8283335) [reply src/include/binder/bind_node_visitor.h]: I've changed this to switch.

File: src/include/binder/bind_node_visitor.h (hunk 9 above)
Comment (wgy8283335) [reply src/include/binder/bind_node_visitor.h]: @mbutrovich THX. I've modified this according to your suggestion.

Comment (wgy8283335) [reply src/include/binder/bind_node_visitor.h]: @apavlo I‘ve committed the modification.

**Comment by wgy8283335** [comment]
@apavlo Dear Professor Pavlo. I've modified the codes, do you think it is good enough to be merged?

File: src/traffic_cop/traffic_cop_util.cpp [hunk 10]
```diff
@@ -55,7 +55,6 @@ std::unique_ptr<planner::AbstractPlanNode> TrafficCopUtil::Optimize(
         sort_dirs.push_back(types[idx] == parser::OrderType::kOrderAsc ? optimizer::OrderByOrderingType::ASC
                                                                        : optimizer::OrderByOrderingType::DESC);
       }
-
```
Comment (lmwnshn) [inline src/traffic_cop/traffic_cop_util.cpp:58]: Unnecessary formatting?

File: src/binder/bind_node_visitor.cpp [hunk 11]
```diff
@@ -495,6 +493,12 @@ void BindNodeVisitor::Visit(common::ManagedPointer<parser::SelectStatement> node
   node->SetSelectColumns(new_select_list);
   node->SetDepth(context_->GetDepth());
 
+  if (node->GetSelectOrderBy() != nullptr) {
+    auto order_by_expressions = UnifyOrderByExpression(node->GetSelectOrderBy(), node->GetSelectColumns());
+    node->GetSelectOrderBy()->GetOrderByExpressions().swap(order_by_expressions);
```
Comment (lmwnshn) [inline src/binder/bind_node_visitor.cpp:498]: I'm a little suspicious of this swap.

If the swap is necessary, then there should be new expressions being created, but I don't see them being added to the parse result.

If the swap is not necessary, because you took a reference to the original order by expressions and directly modified that, then the swap should probably be removed.

File: src/traffic_cop/traffic_cop_util.cpp (hunk 10 above)
Comment (wgy8283335) [reply src/traffic_cop/traffic_cop_util.cpp]: Yes, I will fix this.

File: src/binder/bind_node_visitor.cpp (hunk 11 above)
Comment (wgy8283335) [reply src/binder/bind_node_visitor.cpp]: @lmwnshn thank you for your suggestion. And I have removed the swap and modified the UnifyOrderByExpression function.

**Comment by wgy8283335** [comment]
@apavlo. Dear professor，I'm very excited about the merging because it is my first contribution to the terrier project, thank you. I've attended 15-721 and 15-445 lessons and read some optimization related papers and codes in the optimizer, binder, storage directory of the terrier project. I'd like to spend 2 hours on the countributing to the terrier project every day.  Optimization is my favorite part of the database, and if you have some optimization related task need to be done by a contributor, please let me know, I am very happy to do.

**Comment by apavlo** [comment]
@wgy8283335 Email me
