### PR TITLE
Fix block access controller test

### LINKED ISSUE #490: Probable Race Condition in Block Access Controller
Summary: When compiled for release there appears to be an infrequent race condition that will cause the BlockAccessControllerTest to fail the assertion on line 116 which ensures that WaitUntilHot will guarantee all locks are released before making a block hot.

### Test results
```
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from BlockAccessControllerTest
[ RUN      ] BlockAccessControllerTest.SingleReader
[       OK ] BlockAccessControllerTest.SingleReader (0 ms)
[ RUN      ] BlockAccessControllerTest.WriterPreemption
[       OK ] BlockAccessControllerTest.WriterPreemption (0 ms)
[ RUN      ] BlockAccessControllerTest.FreezingBlocksBoth
[       OK ] BlockAccessControllerTest.FreezingBlocksBoth (11 ms)
[ RUN      ] BlockAccessControllerTest.ReaderWriter
[       OK ] BlockAccessControllerTest.ReaderWriter (11 ms)
[ RUN      ] BlockAccessControllerTest.MultipleReaders
../test/storage/block_access_controller_test.cpp:116: Failure
Value of: REACHED(reader1_released) && REACHED(reader1_released)
  Actual: false
Expected: true
[  FAILED  ] BlockAccessControllerTest.MultipleReaders (17 ms)
[----------] 5 tests from BlockAccessControllerTest (39 ms total)

[----------] Global test environment tear-down
[==========] 5 tests from 1 test case ran. (39 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] BlockAccessControllerTest.MultipleReaders
```

### Steps to reproduce:
```bash
cmake -DCMAKE_BUILD_TYPE=release -DTERRIER_USE_ASAN=off -DBUILD_WARNING_LEVEL=production
make -j
release/block_access_controller_test --gtest_repeat=-1 --gtest_throw_on_failure
```

### Notes:
Building in release mode results in the following warnings:
> ../src/include/storage/block_access_controller.h: In member function ‘std::pair<terrier::storage::BlockState, unsigned int> terrier::storage::BlockAccessController::AtomicallyLoadMembers()’:
> ../src/include/storage/block_access_controller.h:128:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>      return *reinterpret_cast<std::pair<BlockState, uint32_t> *>(&curr_value);
>                                                                             ^
> ../src/include/storage/block_access_controller.h:128:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
> ../src/include/storage/block_access_controller.h: In member function ‘bool terrier::storage::BlockAccessController::UpdateAtomically(const std::pair<terrier::storage::BlockState, unsigned int>&, std::pair<terrier::storage::BlockState, unsigned int>)’:
> ../src/include/storage/block_access_controller.h:134:63: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
>          expected_bytes, *reinterpret_cast<uint64_t *>(&desired));
>                                                                ^

### Initial suspicions:
We are using a struct of two `uin32_t`s to pass the 64-bit type value, which means the values are not guaranteed to be placed 64-bit aligned.  This could cause us to lose the atomicity we are expecting in the code.

### PR DESCRIPTION
**Pull request by tli2**
Fix #490

### CODE REVIEW

**Comment by mbutrovich** [comment]
Thanks for the quick fix! Is it possible to handle the warnings on GCC Release in this PR as well?
```
/jenkins/workspace/terrier_PR-493/src/include/storage/block_access_controller.h:128:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/jenkins/workspace/terrier_PR-493/src/include/storage/block_access_controller.h: In member function ‘bool terrier::storage::BlockAccessController::UpdateAtomically(const std::pair<terrier::storage::BlockState, unsigned int>&, std::pair<terrier::storage::BlockState, unsigned int>)’:
/jenkins/workspace/terrier_PR-493/src/include/storage/block_access_controller.h:134:63: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         expected_bytes, *reinterpret_cast<uint64_t *>(&desired));
```

File: test/storage/block_access_controller_test.cpp [hunk 1]
```diff
@@ -89,31 +89,31 @@ TEST(BlockAccessControllerTest, ReaderWriter) {
...
       EXPECT_TRUE(tested.TryAcquireInPlaceRead());
       PROGRAM_POINT(reader2_acquired)
+      PROGRAM_POINT(reader2_releasing)
       tested.ReleaseInPlaceRead();
-      PROGRAM_POINT(reader2_released)
     });
     WAIT_UNTIL(reader1_acquired && reader2_acquired)
     tested.WaitUntilHot();
-    EXPECT_TRUE(REACHED(reader1_released) && REACHED(reader1_released));
+    EXPECT_TRUE(REACHED(reader1_releasing) && REACHED(reader1_releasing));
```
Comment (GustavoAngulo) [inline test/storage/block_access_controller_test.cpp]: I think this should be `REACHED(reader1_releasing) && REACHED(reader2_releasing)`? You have `reader1_releasing` twice here

Comment (tli2) [reply test/storage/block_access_controller_test.cpp]: Good catch.
